# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sequence Variant Nomenclature
email: VarNomen @ HGVS.org
description: >  # this means to ignore newlines until "baseurl:"
    The consistent and unambiguous description of sequence variants is essential to report and exchange information on the analysis of a genome. In particular, DNA diagnostics critically depends on accurate and standardised description and sharing of the variants detected. The sequence variant nomenclature system proposed in 2000 by the Human Genome Variation Society has been widely adopted and has developed into an internationally accepted standard.
baseurl: "/VarNomen"  # the subpath of your site, e.g. /blog
url: "http://www.HGVS.org/varnomen"  # the base hostname & protocol for your site
version: 15.11  # Current nomenclature version number
collections:
    recommendations:
        output: true
        permalink: /recommendations/:path/
    bg-material:
        output: true
        permalink: /bg-material/:path/
variant-priority:   # used when generating order of variants in site structure and display
# Case-sensitive - use lowercase
    - substitution
    - deletion
    - inversion
    - duplication
    - conversion
    - insertion
    - deletion/ insertion (indel)  
    - alleles
    - repeated sequences
    - complex (HGVS/ISCN)
    # RNA specific
    - RNA processing/ initiation
    - splicing
    - large deletions
    - uncertainties
    # protein specific
    - silent
    - variable short sequence repeats
    - extension

# Build settings
markdown: kramdown  # DOCS: http://kramdown.gettalong.org/syntax.html
