# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sequence Variant Nomenclature
email: VarNomen @ HGVS.org
description: >  # this means to ignore newlines until "baseurl:"
    These pages summarise HGVS-nomenclature: the recommendations for the description of sequence variants. HGVS-nomenclature is used to report and exchange information regarding variants found in DNA, RNA and protein sequences and serves as an international standard in DNA diagnostics. HGVS-nomenclature is authorised by the Human Genome Variation Society (HGVS), the Human Variome Project (HVP) and the HUman Genome Organization (HUGO).
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://varnomen.hgvs.org/"  # the base hostname & protocol for your site
version: 15.11  # Current nomenclature version number
collections:
    recommendations:
        output: true
        permalink: /recommendations/:path/
    bg-material:
        output: true
        permalink: /bg-material/:path/
variant-priority:   # used when generating order of variants in site structure and display
# Case-sensitive - use lowercase
    - substitution
    - deletion
    - duplication
    - insertion
    - inversion
    - conversion
    - deletion/ insertion (indel)
    - deletion-insertion
    - alleles
    - repeated sequences
    - complex (HGVS/ISCN)
    # RNA specific
    - splicing
    # protein specific
    - frame shift
    - extension

# Build settings
markdown: kramdown  # DOCS: http://kramdown.gettalong.org/syntax.html
