# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sequence Variant Nomenclature
email: VarNomen @ HGVS.org
description: >  # this means to ignore newlines until "baseurl:"
    This site covers <b>HGVS-nomenclature</b>, the recommendations for the description of sequence variants. It is used to report and exchange information of variants found in DNA, RNA and protein sequences and serves as an international standard. When using the recommendations please cite: <i><a href='http://onlinelibrary.wiley.com/doi/10.1002/humu.22981/abstract' target='_blank'>Den Dunnen et al. 2016, Hum.Mutat. 37:564-569</a></i>. HGVS-nomenclature is authorised by the Human Genome Variation Society (HGVS), the Human Variome Project (HVP) and the Human Genome Organization (HUGO). Please support our efforts: <a href="https://www.paypal.com/donate/?hosted_button_id=DHJVLF3Z2TA2U" target="\_blank"><img height="20px" src="{{ site.baseurl }}/assets/donate.gif"></img></a> <a href="https://www.paypal.com/donate/?hosted_button_id=DHJVLF3Z2TA2U" target="\_blank"><img height="20px" src="{{ site.baseurl }}/assets/GVdonationQRcode.png"></img></a>
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://varnomen.hgvs.org/"  # the base hostname & protocol for your site
version: 20.05  # Current nomenclature version number
collections:
    recommendations:
        output: true
        permalink: /recommendations/:path/
    bg-material:
        output: true
        permalink: /bg-material/:path/
variant-priority:   # used when generating order of variants in site structure and display
# Case-sensitive - use lowercase
    - substitution
    - deletion
    - duplication
    - insertion
    - inversion
    - deletion-insertion
    - alleles
    - repeated sequences
    - complex (HGVS/ISCN)
    - other
    # RNA specific
    - splicing
    # protein specific
    - frame shift
    - extension

# Build settings
markdown: kramdown  # DOCS: http://kramdown.gettalong.org/syntax.html
