# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sequence Variant Nomenclature
email: VarNomen @ HGVS.org
description: > # this means to ignore newlines until "baseurl:"
    HGVS / HVP / HUGO Sequent Variant Nomenclature
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
collections:
    recommendations:
        output: true
    bg-material:
        output: true
    recent:
        output: true
    contact:
        output: true

# Build settings
markdown: kramdown
