# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Variant Nomenclature
email: VarNomen @ HGVS.org
description: > # this means to ignore newlines until "baseurl:"
    HGVS / HVP / HUGO Sequent Variant Nomenclature
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
collections:
- recommendations:
    path: "" # i.e. all files in /recommendations
    type: recommendations
    values:
        layout: rec 

# Build settings
markdown: kramdown
